### ISSUE TITLE
대여금액과 할인금액의 올바른 계산

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Calculator-LateFee#3]
[새로운 결제 및 반납 화면의 구성](https://github.com/opencloset/opencloset/issues/1277)

    정상금액: 대여품목의 의류가격의 합

으로 계산하고 있습니다.

    정상금액은 order_detail 에서 clothes_code 가 NULL 이 아니고 stage 가 0 인 항목들의 price 의 합

으로 계산하도록 바꾸고 테스트코드를 강화해야 합니다.
다양한 케이스별 테스트를 추가해서 검증해야 합니다.

**Comment by aanoaa** [comment]
온라인주문서의 경우 발송대기때까지 의류코드가 기록되지 않습니다.

    온라인주문서의 대여금액
    의류코드가 지정된 후: 오프라인과 동일함
    의류코드가 지정되기 전: order_detail.name 이 알파벳으로 시작하는 항목의 price 의 합

**Comment by aanoaa** [comment]
할인금액 계산법

    # 온라인
    할인금액: order_detail.name 이 '3회 이상 대여 할인' 인 항목의 price

    # 오프라인
    할인금액: 의류의 본래가격 - order_detail.desc 가 '3회 이상 방문' 인 의류항목의 가격

    #   셔츠가 5,000 인데 셋트이외무료일 경우에는 price 가 0, 5000 - 0 = 5000 이므로 할인금액은 5,000
    #   자켓은 10,000 인데 30% 할인 경우에는 price 가 7000, 10000 - 7000 = 3000 이므로 할인금액은 3,000

**Comment by aanoaa** [comment]
또 헛갈렸는데, 정상금액과 대여금액은 다릅니다.
용어부터 분명히 하면

- 정상금액은 대여 의류품목 가격의 합
- 할인금액은 의류품목의 가격(clothes.price)과 항목의 가격(order_detail.price) 차의 합과 할인항목의 가격
- 대여금액은 정상금액에서 할인금액을 제외한 금액(지불해야할 최종금액)

-------------------------------

`OpenCloset-Calculator-LateFee` 에서는 정상금액과 할인금액을 계산하는 메소드를 제공합니다.

할인항목

- `order_detail.name = '3회 이상 대여 할인'`
- `order_detail.desc LIKE '3회 이상 방문%'`
- `order_detail.name LIKE '%\% 할인쿠폰'`
- `order_detail.name LIKE '%원 할인쿠폰'`

**Comment by aanoaa** [comment]
> 정상금액은 order_detail 에서 clothes_code 가 NULL 이 아니고 stage 가 0 인 항목들의 price 의 합

이것은 잘못된 것 입니다.

    대여금액은 order_detail 에서 clothes_code 가 NULL 이 아니고 stage 가 0 인 항목들의 price 의 합

으로 바뀌어야 합니다.

의류항목의 금액을 변경했다면, 그 차액만큼 할인금액으로 간주되어야 합니다.
하지만 대여금액은 정상금액과 할인금액으로 계산할 수 있습니다.

**Comment by aanoaa** [comment]
정상금액은 suit 타입 쿠폰일때에 연체/연장비 계산을 위해서 사용되고,
대여금액은 그외의 경우에 사용됩니다.
할인금액은 대여금액을 계산하기 위해 필수 입니다.(안내에도 사용됩니다)

suit 타입 쿠폰의 대여금액은 `0원` 입니다.

**Comment by aanoaa** [comment]
의류항목의 금액의 변경

정상금액 20,000 주문서에서 자켓이 `10,000` 인데 어떤 이유에서건 이것을 `15,000` 으로 변경한다면 할인금액에 영향을 미칩니다.

> 할인금액은 의류품목의 가격(clothes.price)과 항목의 가격(order_detail.price) 차의 합과 할인항목의 가격

할인금액이 `-5,000` 이 되고 `25,000` 이 대여금액이 됩니다.

    대여금액 = 정상금액 - 할인금액

이므로 `25,000` 이 대여금액이 됩니다.

**Comment by aanoaa** [comment]
미납금은 반납할때에 결정됩니다.
이를 테스트하기 위해서는 `대여중 -> 반납` 의 기능이 필요합니다.

**Comment by aanoaa** [comment]
에누리 가격이 할인금액에 포함되어야 하는지 검토해봐야 합니다.

**Comment by aanoaa** [comment]
연체료 8,000
    연장료 12,000
    연체/연장료 에누리 1,000

에누리 전/후 가격을 알고 싶을 것 같은데,
일단 에누리 가격은 무시하겠습니다.

**Comment by aanoaa** [comment]
- 정상금액(본래 의류정상가 대여비)
- 할인금액(3회이상 대여 및 쿠폰을 사용했을때의 할인금액)
- 대여금액(정상금액 - 할인금액 + @) : 결제금액입니다.

`@` 는 에누리 금액 및 연장일에 따른 추가 금액입니다.
하나의 개념이 더 필요합니다.

`일일대여금금액`

이것이 연장/연체비를 계산하는 기준이 됩니다.

**Comment by 10001if** [comment]
@aanoaa 생각보다 정말 복잡하네요..

**Comment by aanoaa** [comment]
일일대여금액도 틀렸습니다.
일일이 붙으면 안됩니다.
`3박4일 기준 대여금액` 이 필요합니다.

**Comment by aanoaa** [comment]
의존성 문제가 있습니다.

OpenCloset::Calculator::LateFee(이하 calc)
OpenCloset::API::Order(이하 api)

calc 에서는 api 를 사용하고 api 에서는 calc 를 사용합니다.
calc 에서는는 test 할때만 사용하고 api 에서는 lib 에서도 사용합니다.

**Comment by aanoaa** [comment]
[OpenCloset-Calculator-LateFee-v0.3.0.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Calculator-LateFee-v0.3.0.tar.gz) 배포하였습니다.
